#!/usr/bin/expect

set timeout 2
set PASSWD "mypassword"

eval spawn $argv

while { 1 } {
    expect {
        "(yes/no)?" { send "yes\r" }
        "Password:" { send "$PASSWD\r" }
        "password:" { send "$PASSWD\r" }
        "wxf:" { send "$PASSWD\r" }
        eof { break }
    }
}
