#!/bin/bash
# Usage:
# in normal terminal,
# [ wxf@myhost ] tmux new-session ./mssh
# or in tmux mode terminal:
# [ wxf@myhost ] ./mssh

my_cluster_hosts="
xxx.xxx.xxx.xxx.xxx
xxx.xxx.xxx.xxx.xxx
xxx.xxx.xxx.xxx.xxx
xxx.xxx.xxx.xxx.xxx
xxx.xxx.xxx.xxx.xxx
xxx.xxx.xxx.xxx.xxx
xxx.xxx.xxx.xxx.xxx
xxx.xxx.xxx.xxx.xxx
xxx.xxx.xxx.xxx.xxx
";

HOSTS=${my_cluster_hosts}
tmux new-window "ssh ${HOSTS[0]}"
unset ${HOSTS[0]}
for host in ${HOSTS[@]}
do
    tmux split-window -h "ssh $host"
    tmux select-layout tiled
done
tmux select-pane -t 0
tmux set-window-option synchronize-panes on
